# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: amdavidson
email: hello@amdavidson.com
description: More wasted webspace... 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amdavidson.com" # the base hostname & protocol for your site
twitter_username: amdavidson
github_username: amdavidson
permalink: /:year/:month/:title/index.html

exclude: ['Gemfile', 'Gemfile.lock']
gems: ['jekyll-paginate']

# Build settings
markdown: kramdown

# Pagination Settings
paginate: 5
paginate_path: '/page:num/'

